// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpwwwapubtxqqfcpbdyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwd3d3YXB1YnR4cXFmY3BiZHlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NjU1NDAsImV4cCI6MjA2MzQ0MTU0MH0.Uy7bRuc6KjOkI92YT_lxh1FnhJk8YaKlf02sRcwsEms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);